version: "3"
services:
  express:
    container_name: express
    restart: no
    build: 
      context: ../..
      dockerfile: ./06-deploy/02-docker/Dockerfile.jlg
    ports:
      - "20000:9000"
      - "20443:9443"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:
