version: "3"
services:
  express:
    container_name: express
    restart: always
    build: 
      context: ../../05-rest
      dockerfile: ./../06-deploy/02-docker/Dockerfile
    ports:
      - "49160:9000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata:
